### ISSUE TITLE
Experimental setup and measure

### ISSUE THREAD

**Issue by fvella** [jecoz/parcobench#1]
Did you use the batch system or just slurm-ctrl? 
The potential issue on slurm-ctrl is the concurrent use of resources by other users. 
The batch system guarantees the exclusive use of the CPU. 

How many run for each experiment? Mean and std-dev of the time over multiple executions are good instruments for getting valuable results.

**Comment by dmorn** [comment]
@fvella I'm using the batch system, `sbatch` with the `-W` flag that makes it wait till the command exits https://github.com/jecoz/introparco-12286/blob/e9ccd7a9c9e338a241974004e13f8a6d6f7f9d01/lab00/scripts/remotebench.sh#L45

**Comment by dmorn** [comment]
@fvella I ran the benchmark (with arrays with `n` from 1000 to 100_000, step 1000) something like 5 times for each configuration. The data used for plotting is the mean grouped by `n`. I could add std deviation! https://github.com/jecoz/introparco-12286/blob/e9ccd7a9c9e338a241974004e13f8a6d6f7f9d01/lab00/scripts/mkplot.R#L38
